CREATE TABLE [dbo].[RostersIncomingSchoolsResults]
(
[SCHOOLID_TYPE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SCHL_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAIL_NAME] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAILINGADD1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAILINGADD2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAILINGCITY] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAILINGSTATE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAILINGZIP] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAILINGCOUNTRY] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHYSICALADD1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHYSICALADD2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHYSICALCITY] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHYSICALSTATE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHYSICALZIP] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHYSICALCOUNTRY] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHONE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FAX] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMAIL] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SCHL_STATUS] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WEBSITE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORGANIZATION_TYPE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIST_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIST_NAME] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE_ESTABLISHED] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REC_MOD_DATE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TEACHING_STAFF_COUNT] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FED_TAX_NUM] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LAST_STAT_YR] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TOTAL_SCHOOL_ENROLL] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CC_FULLDAY] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRESCHOOL] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRESCHOOL_HALFDAY] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRESCHOOL_FULLDAY] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[K_HALFDAY] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[K_FULLDAY] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EC_TOTAL_ENROLL] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FEES_MEM_EC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FEES_MEM_K_HALFDAY] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FEES_MEM_K_FULLDAY] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FEES_NONM_EC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FEES_NONM_K_HALFDAY] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FEES_NONM_K_FULLDAY] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EL] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRADE_1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRADE_2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRADE_3] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRADE_4] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRADE_5] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRADE_6] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRADE_7] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRADE_8] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EL_TOTAL_ENROLL] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FEES_MEM_GRD1_3] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FEES_MEM_GRD4_6] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FEES_MEM_GRD7_8] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FEES_NONM_GRD1_3] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FEES_NONM_GRD4_6] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FEES_NONM_GRD7_8] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HS] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRADE_9] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRADE_10] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRADE_11] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRADE_12] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HS_TOTAL_ENROLL] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FEES_MEM_HS] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FEES_NONM_HS] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceModifiedDate] [date] NULL,
[DwSourceName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DwInsertDate] [datetime] NOT NULL,
[DwInsertUsername] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DwInsertProcessName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DwUpdateDate] [datetime] NOT NULL,
[DwUpdateUsername] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DwUpdateProcessName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
