CREATE TABLE [dbo].[RostersIncomingEducators]
(
[CW_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FIRST_NAME] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MIDDLE_NAME] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LAST_NAME] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUFFIX] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLASS_NAME] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIST_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIST_NAME] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YEARS_HERE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRADE_EC] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRADE_K] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRADE_1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRADE_2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRADE_3] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRADE_4] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRADE_5] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRADE_6] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRADE_7] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRADE_8] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRADE_9] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRADE_10] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRADE_11] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GRADE_12] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FULLTIME] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LUTH_TEACHING_YRS] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OTHER_TEACHING_YRS] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATS_MOD_DATE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORGID_TYPE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SCHL_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SCHL_NAME] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CITY] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATE_CODE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COUNTRY] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CURRENT_TEACHING_MOD_DATE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceModifiedDate] [date] NULL,
[DwSourceName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DwInsertDate] [datetime] NOT NULL,
[DwInsertUsername] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DwInsertProcessName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DwUpdateDate] [datetime] NOT NULL,
[DwUpdateUsername] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DwUpdateProcessName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
