CREATE TABLE [dbo].[ACQ_PAPOSITION]
(
[COMPANY] [smallint] NULL,
[R_POSITION] [char] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESCRIPTION] [char] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POSIT_STATUS] [tinyint] NULL,
[EFFECT_DATE] [datetime] NULL,
[END_DATE] [datetime] NULL,
[JOB_CODE] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROCESS_LEVEL] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEPARTMENT] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_LEVEL] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXP_COMPANY] [smallint] NULL,
[EXP_ACCT_UNIT] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXP_ACCOUNT] [int] NULL,
[EXP_SUB_ACCT] [smallint] NULL,
[PAY_RATE] [decimal] (13, 4) NULL,
[SALARY_CLASS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAY_FREQUENCY] [tinyint] NULL,
[SCHEDULE] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAY_GRADE] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAY_STEP] [smallint] NULL,
[SUPERVISOR] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHIFT] [tinyint] NULL,
[UPDATE_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LOCAT_CODE] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UNION_CODE] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BARGAIN_UNIT] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHG_REASON] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACTIVITY] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACCT_CATEGORY] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OT_PLAN_CODE] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUPERVISOR_IND] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUPERVISOR_LNK] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WORK_SCHED] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXEMPT_EMP] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SEC_LVL] [tinyint] NULL,
[SEC_LOCATION] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE_STAMP] [datetime] NULL,
[TIME_STAMP] [decimal] (6, 0) NULL,
[USER_ID] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OBJ_ID] [decimal] (12, 0) NULL,
[ANNUAL_HOURS] [decimal] (8, 4) NULL,
[CURRENCY_CODE] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CURR_ND] [tinyint] NULL,
[BASE_CURRENCY] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BASE_ND] [tinyint] NULL,
[BASE_PAY_RATE] [decimal] (13, 4) NULL,
[ENCUMBER_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CREATE_DATE] [datetime] NULL,
[CREATE_TIME] [decimal] (6, 0) NULL,
[CREATE_USER] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UPDATED_BY_LTM] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L_INDEX] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POSSET20_SS_SW] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POSSET4_SS_SW] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L_ATPOS_SS_SW] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CT_COMPANY] [smallint] NULL,
[CT_R_POSITION] [char] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CT_EFFECT_DATE] [datetime] NULL,
[CHANGE_TYPE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRIMARYKEY] [char] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwInsertDate] [datetime] NULL,
[DwInsertUsername] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwInsertProcessName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwUpdateDate] [datetime] NULL,
[DwUpdateUsername] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwUpdateProcessName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
