CREATE TABLE [dbo].[CpsToBasLawsonEdfFile]
(
[LineId] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EmployerNumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberSsn] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberNumber] [int] NULL,
[LastName] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleName] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Birthdate] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address3] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (58) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Postal] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Country] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressEffDate] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FILLER_1] [int] NULL,
[WorkPhoneNum] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FILLER_2] [int] NULL,
[WorkEmailAddress] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FILLER_3] [int] NULL,
[OriginalHireDate] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LatestHireDate] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmploymentStatusCode] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EmploymentStatusEffDate] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeathDate] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TerminationDate] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FILLER_4] [int] NULL,
[FILLER_5] [int] NULL,
[PayFrequencyCode] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PayFrequencyEffDate] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmployerTaxId] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmployerTaxIdEffDate] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FullOrPartTimeCode] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FullOrPartTimeEffDate] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FILLER_6] [int] NULL,
[FILLER_7] [int] NULL,
[FILLER_8] [int] NULL,
[FILLER_9] [int] NULL,
[FILLER_10] [int] NULL,
[FILLER_11] [int] NULL,
[FILLER_12] [int] NULL,
[BenefitsEligDate] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmployerDepartment] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ScheduledHours] [numeric] (7, 2) NULL,
[ScheduledHoursEffDate] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BaseAnnualSalary] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HousingAllowance] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HomeProvidedAmt] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UtilityAllowance] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AnnualCompensationReportAmt] [varchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AnnualCompensationReportEffDate] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JobClass] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Job Title] [int] NULL,
[JobClassEffDate] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SalariedOrHourlyCode] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SalariedOrHourlyEffDate] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RosteredCode] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RosterSsnInd] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RosterEffDate] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FILLER_13] [int] NULL,
[FILLER_14] [int] NULL,
[Salutation] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MaritalStatusCode] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FILLER_15] [int] NULL,
[MissionaryTypeCode] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MissionaryTypeEffDate] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MissionaryForeignCountry] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
