CREATE TABLE [dbo].[ACQ_PREMIUM]
(
[COMPANY] [smallint] NULL,
[PLAN_TYPE] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PLAN_CODE] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[START_DATE] [datetime] NULL,
[GROUP_NAME] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTRIB_TYPE] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CALC_TYPE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SALARY_TYPE] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SALARY_DATE] [decimal] (4, 0) NULL,
[SAL_FIRST_MO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ROUND_METH] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BEF_AFT_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ROUND_TO] [decimal] (9, 4) NULL,
[AMT_MINIMUM] [decimal] (11, 2) NULL,
[AMT_MAXIMUM] [decimal] (11, 2) NULL,
[TABLE_TYPE] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMP_SPS_AGE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AGE_DATE] [decimal] (4, 0) NULL,
[AGE_FIRST_MO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FROM_DATE] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SERV_DATE] [decimal] (4, 0) NULL,
[SERV_FIRST_MO] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMP_CONT] [decimal] (9, 4) NULL,
[COMP_CONT] [decimal] (13, 4) NULL,
[FLEX_CONT] [decimal] (9, 4) NULL,
[RATE_TABLE] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTRIB_BASIS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COST_PER_CVG] [decimal] (9, 2) NULL,
[ANN_AMT_MIN] [decimal] (11, 2) NULL,
[ANN_AMT_MAX] [decimal] (11, 2) NULL,
[PCT_MINIMUM] [decimal] (7, 4) NULL,
[PCT_MAXIMUM] [decimal] (7, 4) NULL,
[COMP_AMT] [decimal] (7, 2) NULL,
[COMP_PCT] [decimal] (7, 4) NULL,
[VAC_MAX_HOURS] [decimal] (6, 3) NULL,
[VAC_COST] [decimal] (5, 2) NULL,
[INCREMENT] [decimal] (5, 2) NULL,
[EMP_CONT_TYPE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONT_TAX_STS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MATCH_OPTION] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MATCH_CALC] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[END_PCT] [smallint] NULL,
[E_COMP_CONT1] [decimal] (7, 2) NULL,
[R_COMP_CONT1] [decimal] (7, 2) NULL,
[RET_RATE_TBL] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATUS] [tinyint] NULL,
[RET_STATUS] [tinyint] NULL,
[EARLY_RT_AGE] [smallint] NULL,
[REG_RT_AGE] [smallint] NULL,
[FLEX_CONT1] [decimal] (7, 2) NULL,
[DEFAUL_TAX_TYP] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SALARY_YEAR] [smallint] NULL,
[AGE_YEAR] [smallint] NULL,
[SERV_YEAR] [smallint] NULL,
[PAY_PER_MIN] [decimal] (6, 2) NULL,
[PAY_PER_MAX] [decimal] (6, 2) NULL,
[COVER_TYPE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COBRA_STATUS] [tinyint] NULL,
[CREATE_DATE] [datetime] NULL,
[CREATE_TIME] [decimal] (6, 0) NULL,
[CREATE_USER_ID] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE_STAMP] [datetime] NULL,
[TIME_STAMP] [decimal] (6, 0) NULL,
[USER_ID] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACA_PRIORITY] [int] NULL,
[ACA_OFFER] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACA_SAFEHARBOR] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACA_SELF_INS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACA_WAIVE_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACA_COST] [decimal] (11, 2) NULL,
[CT_COMPANY] [smallint] NULL,
[CT_PLAN_TYPE] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CT_PLAN_CODE] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CT_START_DATE] [datetime] NULL,
[CT_GROUP_NAME] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CT_COVER_TYPE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHANGE_TYPE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRIMARYKEY] [char] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwInsertDate] [datetime] NULL,
[DwInsertUsername] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwInsertProcessName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwUpdateDate] [datetime] NULL,
[DwUpdateUsername] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwUpdateProcessName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
