CREATE TABLE [dbo].[ACQ_EMPLOYEE_old]
(
[COMPANY] [smallint] NULL,
[EMPLOYEE] [int] NULL,
[LAST_NAME] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIRST_NAME] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MIDDLE_INIT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MIDDLE_NAME] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NICK_NAME] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[addr0] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDR1] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDR2] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDR3] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDR4] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CITY] [char] (58) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATE] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZIP] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMP_STATUS] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FICA_NBR] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EIC_STATUS] [tinyint] NULL,
[PROCESS_LEVEL] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEPARTMENT] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USER_LEVEL] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HM_DIST_CO] [smallint] NULL,
[HM_ACCT_UNIT] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HM_ACCOUNT] [int] NULL,
[HM_SUB_ACCT] [smallint] NULL,
[JOB_CODE] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UNION_CODE] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUPERVISOR] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE_HIRED] [datetime] NULL,
[PAY_FREQUENCY] [tinyint] NULL,
[SHIFT] [tinyint] NULL,
[SALARY_CLASS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXEMPT_EMP] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAY_RATE] [decimal] (13, 4) NULL,
[STAND_HOURS] [decimal] (7, 2) NULL,
[STAND_AMT] [decimal] (11, 3) NULL,
[WARN_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADD_ALLOW_PER] [decimal] (7, 3) NULL,
[ADD_ALLOW_HRS] [decimal] (7, 2) NULL,
[ADD_ALLOW_AMT] [int] NULL,
[RPT_INS_COST] [decimal] (11, 2) NULL,
[AUTO_TIME_REC] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LAST_DED_SEQ] [smallint] NULL,
[AUTO_DEPOSIT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADJ_HIRE_DATE] [datetime] NULL,
[ANNIVERS_DATE] [datetime] NULL,
[TERM_DATE] [datetime] NULL,
[LAST_CMT_SEQ] [smallint] NULL,
[CREATION_DATE] [datetime] NULL,
[NBR_FTE] [decimal] (7, 6) NULL,
[PENSION_PLAN] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAY_STEP] [smallint] NULL,
[PAY_GRADE] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SCHEDULE] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EBE_AMOUNT] [decimal] (9, 2) NULL,
[SICK_PAY] [decimal] (11, 2) NULL,
[OT_PLAN_CODE] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DECEASED] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BSI_GROUP] [char] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WORK_STATE] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAX_STATE] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAX_PROVINCE] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WC_STATE] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAX_COUNTY] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAX_CITY] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MOVING_EXP] [decimal] (11, 2) NULL,
[ALT_RATE_EXIST] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PEND_ACT_DATE] [datetime] NULL,
[PIN] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TIPPED] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMAIL_ADDRESS] [char] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACTIVITY] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACCT_CATEGORY] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAX_LIMIT_OVRD] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SEC_LVL] [tinyint] NULL,
[SEC_LOCATION] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[R_POSITION] [char] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WORK_SCHED] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SUPERVISOR_IND] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ANNUAL_HOURS] [decimal] (8, 4) NULL,
[WORK_COUNTY] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WORK_CITY] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WORK_SCHOOL] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WORK_TRANSPORT] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAX_SCHOOL] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAX_TRANSPORT] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FTE_TOTAL] [decimal] (11, 6) NULL,
[PRO_RATE_TOTAL] [decimal] (13, 4) NULL,
[PRO_RATE_A_SAL] [decimal] (13, 4) NULL,
[NEW_HIRE_DATE] [datetime] NULL,
[CURRENCY_CODE] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CURR_ND] [tinyint] NULL,
[COUNTRY_CODE] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NAME_PREFIX] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NAME_SUFFIX] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WORK_COUNTRY] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LAST_NAME_PRE] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EST_REMUN] [decimal] (11, 2) NULL,
[EST_EXPENSE] [decimal] (11, 2) NULL,
[BUS_NBR_GRP] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QC_ENT_NBR_GRP] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WC_PROVINCE] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COUNTY] [char] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RAILROAD_CODE] [tinyint] NULL,
[FST_DAY_WORKED] [datetime] NULL,
[LAST_DAY_PAID] [datetime] NULL,
[LAB_DIST_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ENCUMBER_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFFORT_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RPT_CURR] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRMCERT_ID] [int] NULL,
[SNDCERT_ID] [int] NULL,
[FRNG_RATE] [decimal] (12, 6) NULL,
[FRNG_ACCT_CAT] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FRNG_ACCOUNT] [int] NULL,
[FRNG_SUB_ACCT] [smallint] NULL,
[DEATH_DATE] [datetime] NULL,
[TAX_FILTER] [tinyint] NULL,
[REMOTE] [tinyint] NULL,
[PUB_SEC_RETIRE] [smallint] NULL,
[PRMCERT_COMP] [smallint] NULL,
[SNDCERT_COMP] [smallint] NULL,
[ST_STATUS] [tinyint] NULL,
[LAST_NAME_UC] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIRST_NAME_UC] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FICA_NBR_LAST4] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMAIL_PERSONAL] [char] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UPDATED_BY_LTM] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HICN] [char] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L_INDEX] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L_ATEMP_SS_SW] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CT_COMPANY] [smallint] NULL,
[CT_EMPLOYEE] [int] NULL,
[CHANGE_TYPE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRIMARYKEY] [char] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwInsertDate] [datetime] NULL,
[DwInsertUsername] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwInsertProcessName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwUpdateDate] [datetime] NULL,
[DwUpdateUsername] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwUpdateProcessName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
