CREATE TABLE [dbo].[ACQ_EMDEPEND]
(
[COMPANY] [smallint] NULL,
[EMPLOYEE] [int] NULL,
[SEQ_NBR] [smallint] NULL,
[REL_CODE] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LAST_NAME] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIRST_NAME] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MIDDLE_INIT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMP_ADDRESS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDR1] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDR2] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDR3] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDR4] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CITY] [char] (58) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATE] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZIP] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FICA_NBR] [char] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HM_PHONE_CNTRY] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HM_PHONE_NBR] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WK_PHONE_CNTRY] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WK_PHONE_NBR] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WK_PHONE_EXT] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BIRTHDATE] [datetime] NULL,
[HL_COV_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DN_COV_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DL_COV_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEP_TYPE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SEX] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STUDENT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DISABLED] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMOKER] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRIMARY_CARE] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADOPTION_DATE] [datetime] NULL,
[PLACEMENT_DATE] [datetime] NULL,
[NAME_SUFFIX] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LAST_NAME_PRE] [char] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COUNTRY_CODE] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONSENT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACTIVE_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE_STAMP] [datetime] NULL,
[TIME_STAMP] [decimal] (6, 0) NULL,
[USER_ID] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DECEASED] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEATH_DATE] [datetime] NULL,
[ESTAB_PATIENT] [tinyint] NULL,
[PRIOR_COV_MO] [smallint] NULL,
[MEDICARE_IND] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VS_COV_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STUDENT_VERIFY] [datetime] NULL,
[EMAIL_PERSONAL] [char] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HICN] [char] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEP_OF] [smallint] NULL,
[DISABILITY_SEV] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L_INDEX] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L_ATEMD_SS_SW] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CT_COMPANY] [smallint] NULL,
[CT_EMPLOYEE] [int] NULL,
[CT_SEQ_NBR] [smallint] NULL,
[CHANGE_TYPE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRIMARYKEY] [char] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwInsertDate] [datetime] NULL,
[DwInsertUsername] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwInsertProcessName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwUpdateDate] [datetime] NULL,
[DwUpdateUsername] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwUpdateProcessName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
