CREATE TABLE [dbo].[BasEmployerElection_old_del]
(
[ERNumber] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmployerFullName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanYear] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FederalEIN] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WorkZipCode] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Exempt_NonExempt] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QCCOIndicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LimitedAdoptionIndicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CDSPEligIndicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SuppLifeEligIndicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccidentInsuranceEligIndicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CriticalIllnessEligIndicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ADDEligIndicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRPPlanTraditional] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRPPlanAccountOption] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRPWaitingPeriodFlag] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRPAcctOptionEligFactor] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRSPElig] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHPMEDHours] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHPDENHours] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHPVISHours] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ICAccess] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayFrequency] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CategoryofActualparticipation] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AOLastEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AOOriginalEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChangeDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Med1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Med2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Med3] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GEOBlue_Option1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GEOBlue_Option2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DentalUnbundled] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DentalBundledNonHMO] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DentalBundledHMO] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GEOBlueDental] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VisionUnbundled] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VisionBundled] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GEOBlueVision] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PSA] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
