CREATE TABLE [dbo].[RostersIncomingHeadquartersResults_del]
(
[RSO_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HQ_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LRSS_SCHL_ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSO_Name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAILINGADD1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAILINGADD2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAILINGCITY] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAILINGSTATE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAILINGZIP] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MAILINGCOUNTRY] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHYSICALADD1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHYSICALADD2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHYSICALCITY] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHYSICALSTATE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHYSICALZIP] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHYSICALCOUNTRY] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PHONE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FAX] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMAIL] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RSO_TYPE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WEBSITE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIST_NAME] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SITE_COUNT] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTACT_TITLE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTACT_FIRST_NAME] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTACT_LAST_NAME] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTACT_EMAIL] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTACT_PHONE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATUS] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACTION_DATE] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceModifiedDate] [date] NULL,
[DwSourceName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DwInsertDate] [datetime] NOT NULL,
[DwInsertUsername] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DwInsertProcessName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DwUpdateDate] [datetime] NOT NULL,
[DwUpdateUsername] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DwUpdateProcessName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
