CREATE TABLE [dbo].[ERR_EmployeeStatementOfBenefits]
(
[SYS_CHANGE_OPERATION] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SYS_CHANGE_CONTEXT] [binary] (128) NULL,
[lastversion] [bigint] NULL,
[maxversion] [bigint] NULL,
[ETLupdatetimestamp] [datetime] NULL,
[EmployeeId] [int] NULL,
[EmployeeStatementOfBenefitsId] [int] NULL,
[MemberName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AnnualCompensationDate] [date] NULL,
[AnnualCompensation] [numeric] (19, 4) NULL,
[ErContributionToChp] [numeric] (19, 4) NULL,
[ErContributionToCdsp] [numeric] (19, 4) NULL,
[ErMatchForCrsp] [numeric] (19, 4) NULL,
[CrpProjectedAnnualAmount] [numeric] (19, 4) NULL,
[CrpProjectedAccountBalance] [numeric] (19, 4) NULL,
[CrpProjectedAnnualDate] [date] NULL,
[ChpEnrollmentStatus] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChpOption] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChpParticipation] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CdspEnrollmentStatus] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CdspMonthlyBenefitAmount] [numeric] (19, 4) NULL,
[SbCdspEnrollmentStatus] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SbCdspCurrentParticipation] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SbAipEnrollmentStatus] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SbAipCurrentParticipation] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LsbCdspAmount] [numeric] (19, 4) NULL,
[LsbAipAmount] [numeric] (19, 4) NULL,
[DbCdspEnrolledSpouseAmount] [numeric] (19, 4) NULL,
[DbCdspEnrolledDependentAmount] [numeric] (19, 4) NULL,
[DbCdspDependentName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DbAipEnrolledSpouseAmount] [numeric] (19, 4) NULL,
[DbAipCdspEnrolledDependentAmount] [numeric] (19, 4) NULL,
[DbAipCdspDependentName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CrpEnrollmentStatus] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CrpCurrentParticipation] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CrspEnrollmentStatus] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CrspEstimatedDeferralPercent] [int] NULL,
[CrspEstimatedDeferralDate] [date] NULL,
[CrspBalanceAmount] [numeric] (19, 4) NULL,
[CrspBalanceDate] [date] NULL,
[CT_EmployeeStatementOfBenefitsID] [int] NULL,
[AccidentEnrollmentStatus] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__ERR_Emplo__Accid__7B264821] DEFAULT (NULL),
[AccidentCurrentCoverage] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__ERR_Emplo__Accid__7C1A6C5A] DEFAULT (NULL),
[AccidentCurrentParticipation] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__ERR_Emplo__Accid__7D0E9093] DEFAULT (NULL),
[CritillEmployeeEnrollmentStatus] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__ERR_Emplo__Criti__7E02B4CC] DEFAULT (NULL),
[CritillEmployeeCurrentCoverage] [decimal] (19, 4) NULL CONSTRAINT [DF__ERR_Emplo__Criti__7EF6D905] DEFAULT (NULL),
[CritillSpouseEnrollmentStatus] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__ERR_Emplo__Criti__7FEAFD3E] DEFAULT (NULL),
[CritillSpouseCurrentCoverage] [decimal] (19, 4) NULL CONSTRAINT [DF__ERR_Emplo__Criti__00DF2177] DEFAULT (NULL),
[CritillChildEnrollmentStatus] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__ERR_Emplo__Criti__01D345B0] DEFAULT (NULL),
[CritillChildCurrentCoverage] [decimal] (19, 4) NULL CONSTRAINT [DF__ERR_Emplo__Criti__02C769E9] DEFAULT (NULL),
[SupplifeEmployeeEnrollmentStatus] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__ERR_Emplo__Suppl__03BB8E22] DEFAULT (NULL),
[SupplifeEmployeeCurrentCoverage] [decimal] (19, 4) NULL CONSTRAINT [DF__ERR_Emplo__Suppl__04AFB25B] DEFAULT (NULL),
[SupplifeSpouseEnrollmentStatus] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__ERR_Emplo__Suppl__05A3D694] DEFAULT (NULL),
[SupplifeSpouseCurrentCoverage] [decimal] (19, 4) NULL CONSTRAINT [DF__ERR_Emplo__Suppl__0697FACD] DEFAULT (NULL),
[SupplifeChildEnrollmentStatus] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__ERR_Emplo__Suppl__078C1F06] DEFAULT (NULL),
[SupplifeChildCurrentCoverage] [decimal] (19, 4) NULL CONSTRAINT [DF__ERR_Emplo__Suppl__0880433F] DEFAULT (NULL)
) ON [PRIMARY]
GO
