CREATE TABLE [dbo].[BasIncomingEmployeeDemographic]
(
[BasIncomingEmployeeDemographicId] [int] NOT NULL IDENTITY(1, 1),
[EmployerId] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmployeeSsn] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmployeeId] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleNameOrInitial] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Birthdate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address3] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Postal] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[County] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrimaryPhoneNumber] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WorkPhone] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MobilePhoneNumber] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WorkEmailAddress] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HomeEmailAddress] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginalHireDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LatestHireDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmploymentStatus] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmploymentStatusEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DeathDateAttribute] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TerminationDateAttribute] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BenefitsEligibilityDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmployerDepartmentReporting] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ScheduledHours] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ScheduledHoursEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BaseAnnualSalaryAcrFactor] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AnnualCashHousingAllowanceAcrFactor] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HomeProvidedAmountAcrFactor] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AnnualCashUtilityAllowanceAcrFactor] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalAcrSumOfThreeAbove] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AcrEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JobTitleOrClass] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JobTitleOrClassDescription] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SalariedOrHourlyIndicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SalariedOrHourlyIndicatorEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RosterNonRosterIndicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RosteredOrCommissionedSocialSecurityIndicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RosterNonRosterIndicatorEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Salutation] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MaritalStatus] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MaritalStatusEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LawsonEmployeeId] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MissionaryTypeIndicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MissionCountryCode] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MissionaryTypeEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BilltoEmployerTaip] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChpCostAndBillingOverride] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CdspCostAndBillingOverride] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VoluntaryBenefitsCostAndBillingOverride] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChpCostAndBillngOverrideEndDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CdspCostAndBillngOverrideEndDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChpCostAndBillingOverrideEmployerNumber] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CdspCostAndBillingOverrideEmployerNumber] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VoluntaryBenefitsCostandBillingOverrideEmployerNumber] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VoluntaryBenefitsCostandBillngOverrideEndDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CrpTraditionalRegularFullBasisIndicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CrpTraditionalRegularFullBasisEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Extensiontype] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExtensionPaidThruDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExtensionStartDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExtensionEndDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CpsPreviousEmployerNumber] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MaidenName] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewhireEmailAddress] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TerminationRuleIndicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ConcordiaSalutation] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JobClassEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JobTitleEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TaipEligIndicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TaipEligIndicatorEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TaipDualCoverage] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TaipDualCoverageEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayFrequency] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CrpPlanEligOverride] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CrpPlanEligOverrideEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CrpPercentageRate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CrpPercentageRateEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmploymentDesignation] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmploymentDesignationEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChpLastErOverride] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChpYearsofService] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChpYearsofServiceEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TobaccoAttribute] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TobaccoAttributeEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpouseTobacco] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpouseTobaccoEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PremiumPlusEmployeeInd] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PremiumPlusEmployeeIndEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PremiumPlusSpouseInd] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PremiumPlusSpouseIndEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MedicareEligibleIndicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MedicareEligibleIndicatorEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DisabilityStatus] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DisabilityStatusEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CpsDisabilityNoCHP] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CpsDisabilityNoCHPEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CpsEmployerWaiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CpsLastDayWorkPriortoDis] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CpsDisabWaiverBillToCDSP] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CpsDisabWaiverBillToCDSPEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChpPlanAvailabilityOverride] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChpPlanAvailabilityOverrideEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[3TierOverride] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[3TierOverrideEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChpGrandfatheredIndicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChpGrandfatheredIndicatorEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CdspOverride] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CdspOverrideEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AcaEligibilityOverride] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AcaEligibilityOverrideEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MnSupplifePrevDeniedFlag] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MnSupplifePrevDeniedFlagEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MnSpSupplifePrevDeniedFlag] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MnSpSupplifePrevDeniedFlagEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecurianDirectBillIndicator] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecurianDirectBillIndicatorEffectiveDate] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceModifiedDate] [date] NULL,
[DwSourceName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DwInsertDate] [datetime] NOT NULL,
[DwInsertUsername] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DwInsertProcessName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DwUpdateDate] [datetime] NOT NULL,
[DwUpdateUsername] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DwUpdateProcessName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BasIncomingEmployeeDemographic] ADD CONSTRAINT [PK__BasIncom__6937FD24587CB346] PRIMARY KEY CLUSTERED ([BasIncomingEmployeeDemographicId]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
