CREATE TABLE [dbo].[BasIncomingBillingFileGroup]
(
[BasIncomingBillingFileGroupId] [int] NOT NULL IDENTITY(1, 1),
[CustomerId] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExchangeType] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SponsorExchangeId] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MemberAction] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Relationship] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrimarySubscriberExchangeId] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubscriberExchangeId] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingStartDate] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillingEndDate] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleInitial] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ssn] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone1] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone2] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PostalCode] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DateOfBirth] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RaceCode] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TobaccoUse] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanAction] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CarrierExchangeId] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanExchangeId] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PlanStartDate] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InsuredType] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CoverageLevel] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CoverageStartDate] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CoverageEndDate] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AnnualCost] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MonthlyBillableAmount] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CrpFullRegularBasis] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CrpPlanAccountOption] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AoEligFactor] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CrpWaitingPeriodFlag] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CrpAdjServiceDate] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RosterIndicator] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HourlySalaryIndicator] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalAcr] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecurianDirectBill] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceModifiedDate] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwSourceName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DwInsertDate] [datetime] NOT NULL,
[DwInsertUsername] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DwInsertProcessName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DwUpdateDate] [datetime] NOT NULL,
[DwUpdateUsername] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DwUpdateProcessName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BasIncomingBillingFileGroup] ADD CONSTRAINT [PK__BasIncom__8E8301BD63E25DE3] PRIMARY KEY CLUSTERED ([BasIncomingBillingFileGroupId]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
