CREATE TABLE [dbo].[ACQ_PAYDEDUCTN]
(
[COMPANY] [smallint] NULL,
[EMPLOYEE] [int] NULL,
[CHECK_ID] [decimal] (12, 0) NULL,
[DED_CODE] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROCESS_LEVEL] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WORK_STATE] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAYROLL_YEAR] [smallint] NULL,
[QUARTER] [tinyint] NULL,
[EDM_SEQ_NBR] [smallint] NULL,
[DED_AMT] [decimal] (13, 2) NULL,
[TAX_WAGES] [decimal] (13, 2) NULL,
[WAGE_AMOUNT] [decimal] (13, 2) NULL,
[EXCESS] [decimal] (13, 2) NULL,
[GARN_OBJ_ID] [decimal] (12, 0) NULL,
[REPORT_ENTITY] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BUS_NBR_GRP] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[QC_ENT_NBR_GRP] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OBJ_ID] [decimal] (12, 0) NULL,
[CURRENCY_CODE] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CURR_ND] [tinyint] NULL,
[CHECK_DATE] [datetime] NULL,
[PER_END_DATE] [datetime] NULL,
[BALANCE_TYPE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAX_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HM_PROCESS_LEV] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COUNTRY_CODE] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NI_CODE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIRECTOR] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAX_CODE] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAX_BASIS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERIOD_NBR] [smallint] NULL,
[CONTRACTED_OUT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OT_PLAN_CODE] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CT_COMPANY] [smallint] NULL,
[CT_EMPLOYEE] [int] NULL,
[CT_CHECK_ID] [decimal] (12, 0) NULL,
[CT_DED_CODE] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CT_PROCESS_LEVEL] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CT_WORK_STATE] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CT_EDM_SEQ_NBR] [smallint] NULL,
[CT_REPORT_ENTITY] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CT_BUS_NBR_GRP] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CT_QC_ENT_NBR_GRP] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHANGE_TYPE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRIMARYKEY] [char] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwInsertDate] [datetime] NULL,
[DwInsertUsername] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwInsertProcessName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwUpdateDate] [datetime] NULL,
[DwUpdateUsername] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwUpdateProcessName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
