CREATE TABLE [dbo].[ACQ_EMDEDMASTR]
(
[COMPANY] [smallint] NULL,
[EMPLOYEE] [int] NULL,
[DED_CODE] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SEQ_NBR] [smallint] NULL,
[DED_CYCLE_01] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DED_CYCLE_02] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DED_CYCLE_03] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DED_CYCLE_04] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DED_CYCLE_05] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DED_CYCLE_06] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DED_CYCLE_07] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DED_CYCLE_08] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DED_CYCLE_09] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BALANCE_TYPE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BALANCE_AMT] [decimal] (18, 2) NULL,
[NEXT_AMOUNT] [decimal] (13, 4) NULL,
[DED_PRIORITY] [tinyint] NULL,
[EFFECT_DATE] [datetime] NULL,
[END_DATE] [datetime] NULL,
[ARREARS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCT_MATCHED] [decimal] (5, 2) NULL,
[MONTHLY_LIMIT] [decimal] (11, 2) NULL,
[PAY_PRD_LIMIT] [decimal] (11, 2) NULL,
[PRIORITY_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ARREARS_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EFF_DATE_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[END_DATE_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DED_CYC_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AMOUNT_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AMOUNT_2_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MTH_LIMIT_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRD_LIMIT_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DED_ORDER] [smallint] NULL,
[RES_CODE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MARITAL_STATUS] [smallint] NULL,
[EXEMPTIONS] [int] NULL,
[EXEMPT_AMOUNT] [decimal] (9, 2) NULL,
[CERT_CODE] [tinyint] NULL,
[PERS_EXEMPTS] [tinyint] NULL,
[DEPEND_EXEMPTS] [int] NULL,
[ADDL_EXEMPTS] [int] NULL,
[ADDL_EXEMP_AMT] [decimal] (9, 2) NULL,
[ADDL_TAX_CODE] [smallint] NULL,
[ADDL_RATE] [decimal] (7, 4) NULL,
[ADDL_AMOUNT] [decimal] (9, 2) NULL,
[FORMULA_NUMBER] [smallint] NULL,
[FILING_STATUS] [tinyint] NULL,
[LEVY_EXEMPTS] [smallint] NULL,
[LEVY_YEAR] [smallint] NULL,
[ADDL_STD_DED] [tinyint] NULL,
[OBJ_ID] [decimal] (12, 0) NULL,
[EXP_DIST_CO] [smallint] NULL,
[EXP_ACCT_UNIT] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXP_ACCOUNT] [int] NULL,
[EXP_SUB_ACCT] [smallint] NULL,
[ACR_DIST_CO] [smallint] NULL,
[ACR_ACCT_UNIT] [char] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACR_ACCOUNT] [int] NULL,
[ACR_SUB_ACCT] [smallint] NULL,
[SUB_PRIORITY] [smallint] NULL,
[GARN_OBJ_ID] [decimal] (12, 0) NULL,
[AMOUNT_2] [decimal] (13, 4) NULL,
[NET_CLAIM_AMT] [decimal] (11, 2) NULL,
[PRESCRIBEDAREA] [decimal] (11, 2) NULL,
[STUDENT_PEN_EX] [decimal] (9, 2) NULL,
[TD1_FILING_DAT] [datetime] NULL,
[TD1_ADJUST_DAT] [datetime] NULL,
[APPROVED_STOCK] [decimal] (9, 2) NULL,
[TAX_EXEMPT_FLG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AUTH_TAX_CRED] [decimal] (9, 2) NULL,
[AUTH_TAX_DED] [decimal] (9, 2) NULL,
[MARRIED_EQUIV] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AGE_65_OVER] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMP_DISABILITY] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEP_UNDER_18] [smallint] NULL,
[DEP_DIS_OVR_17] [smallint] NULL,
[CURRENCY_CODE] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CURR_ND] [tinyint] NULL,
[NI_CODE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIRECTOR] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NI_CERT_ISSUED] [datetime] NULL,
[NI_CERT_NBR] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAX_CODE] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TAX_BASIS] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REF_WITHELD] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[P46_ISSUED] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[P46_ISSUE_DATE] [datetime] NULL,
[P45_ISSUED] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[P45_ISSUE_DATE] [datetime] NULL,
[PAY_FREQUENCY] [tinyint] NULL,
[CONTRACTED_OUT] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DFLT_TCA_FLAG] [smallint] NULL,
[HM_PROC_LEVEL] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXCLUDE_AMT] [decimal] (13, 4) NULL,
[EXCL_AMT_FLAG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CREATE_DATE] [datetime] NULL,
[CREATE_TIME] [decimal] (6, 0) NULL,
[CREATE_USER_ID] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE_STAMP] [datetime] NULL,
[TIME_STAMP] [decimal] (6, 0) NULL,
[USER_ID] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TOT_CLM_AMT_FL] [smallint] NULL,
[NON_IND_CL_AMT] [decimal] (10, 2) NULL,
[TRANS_YTD_WAGE] [decimal] (10, 2) NULL,
[TRANS_YTD_TAX] [decimal] (10, 2) NULL,
[TRANS_YEAR] [smallint] NULL,
[CLAIM_CODE] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOIN_LEAVE_FLG] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CT_COMPANY] [smallint] NULL,
[CT_EMPLOYEE] [int] NULL,
[CT_DED_CODE] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CT_SEQ_NBR] [smallint] NULL,
[CHANGE_TYPE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRIMARYKEY] [char] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwInsertDate] [datetime] NULL,
[DwInsertUsername] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwInsertProcessName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwUpdateDate] [datetime] NULL,
[DwUpdateUsername] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwUpdateProcessName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
