CREATE TABLE [dbo].[LAWSON_DIM_COMPARE]
(
[TableName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Discrepancy] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProcessDatetime] [datetime] NULL,
[CompareField] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LawsonValue] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DataWarehouseValue] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COMPANY] [smallint] NULL,
[EMPLOYEE] [int] NULL,
[PLAN_CODE] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PLAN_TYPE] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[START_DATE] [datetime] NULL,
[CUST_GROUP] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CUSTOMER] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SEQ_NBR] [smallint] NULL,
[EMP_STATUS] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEPENDENT] [smallint] NULL,
[EMP_START] [datetime] NULL,
[EMP_APP] [tinyint] NULL,
[FIELD_KEY] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BEG_DATE] [datetime] NULL,
[FLD_NBR] [smallint] NULL,
[OBJ_ID] [decimal] (12, 0) NULL,
[PARTICIPNT] [int] NULL,
[PRIM_CNTGNT] [tinyint] NULL,
[CREATION_DATE] [datetime] NULL,
[UPD_DATE] [datetime] NULL,
[DATE_STAMP] [datetime] NULL,
[CREATE_DATE] [datetime] NULL,
[ETLRowStartDate] [datetime] NULL,
[ETLRowEndDate] [datetime] NULL,
[ETLRowIsCurrent] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwInsertDate] [datetime] NULL,
[DwInsertUsername] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwInsertProcessName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwUpdateDate] [datetime] NULL,
[DwUpdateUsername] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwUpdateProcessName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
