CREATE TABLE [dbo].[ACQ_HRHISTORY]
(
[COMPANY] [smallint] NULL,
[EMPLOYEE] [int] NULL,
[OBJ_ID] [decimal] (12, 0) NULL,
[FLD_NBR] [smallint] NULL,
[BEG_DATE] [datetime] NULL,
[SEQ_NBR] [smallint] NULL,
[N_VALUE] [decimal] (15, 6) NULL,
[A_VALUE] [char] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[D_VALUE] [datetime] NULL,
[ACT_OBJ_ID] [decimal] (12, 0) NULL,
[USER_ID] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DATE_STAMP] [datetime] NULL,
[TIME_STAMP] [decimal] (6, 0) NULL,
[DATA_TYPE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POS_LEVEL] [smallint] NULL,
[CURRENCY_CODE] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CURR_ND] [tinyint] NULL,
[UPDATED_BY_LTM] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HRHSET4_SS_SW] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CT_COMPANY] [smallint] NULL,
[CT_EMPLOYEE] [int] NULL,
[CT_OBJ_ID] [decimal] (12, 0) NULL,
[CT_FLD_NBR] [smallint] NULL,
[CT_BEG_DATE] [datetime] NULL,
[CT_SEQ_NBR] [smallint] NULL,
[CHANGE_TYPE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRIMARYKEY] [char] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwInsertDate] [datetime] NULL,
[DwInsertUsername] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwInsertProcessName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwUpdateDate] [datetime] NULL,
[DwUpdateUsername] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwUpdateProcessName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
