CREATE TABLE [dbo].[EEDemoComparePREV_Demographics]
(
[FINDICATOR] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BasIncomingEmployeeDemographicId] [int] NOT NULL,
[EmployerId] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmployeeSsn] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmployeeId] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleNameOrInitial] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Birthdate] [date] NULL,
[Gender] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address3] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Postal] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[County] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressEffectiveDate] [date] NULL,
[PrimaryPhoneNumber] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WorkPhone] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MobilePhoneNumber] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WorkEmailAddress] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HomeEmailAddress] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginalHireDate] [date] NULL,
[LatestHireDate] [date] NULL,
[EmploymentStatus] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmploymentStatusEffectiveDate] [date] NULL,
[DeathDateAttribute] [date] NULL,
[TerminationDateAttribute] [date] NULL,
[BenefitsEligibilityDate] [date] NULL,
[EmployerDepartmentReporting] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ScheduledHours] [decimal] (7, 2) NULL,
[ScheduledHoursEffectiveDate] [date] NULL,
[BaseAnnualSalaryAcrFactor] [decimal] (30, 2) NULL,
[AnnualCashHousingAllowanceAcrFactor] [decimal] (30, 2) NULL,
[HomeProvidedAmountAcrFactor] [decimal] (30, 2) NULL,
[AnnualCashUtilityAllowanceAcrFactor] [decimal] (30, 2) NULL,
[TotalAcrSumOfThreeAbove] [decimal] (30, 2) NULL,
[AcrEffectiveDate] [date] NULL,
[JobTitleOrClass] [nvarchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JobTitleOrClassDescription] [nvarchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SalariedOrHourlyIndicator] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SalariedOrHourlyIndicatorEffectiveDate] [date] NULL,
[RosterNonRosterIndicator] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RosteredOrCommissionedSocialSecurityIndicator] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RosterNonRosterIndicatorEffectiveDate] [date] NULL,
[Salutation] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MaritalStatus] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MaritalStatusEffectiveDate] [date] NULL,
[LawsonEmployeeId] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MissionaryTypeIndicator] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MissionCountryCode] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MissionaryTypeEffectiveDate] [date] NULL,
[BilltoEmployerTaip] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChpCostAndBillingOverride] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CdspCostAndBillingOverride] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VoluntaryBenefitsCostAndBillingOverride] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChpCostAndBillngOverrideEndDate] [date] NULL,
[CdspCostAndBillngOverrideEndDate] [date] NULL,
[ChpCostAndBillingOverrideEmployerNumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CdspCostAndBillingOverrideEmployerNumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VoluntaryBenefitsCostandBillingOverrideEmployerNumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VoluntaryBenefitsCostandBillngOverrideEndDate] [date] NULL,
[CrpTraditionalRegularFullBasisIndicator] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CrpTraditionalRegularFullBasisEffectiveDate] [date] NULL,
[Extensiontype] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExtensionPaidThruDate] [date] NULL,
[ExtensionStartDate] [date] NULL,
[ExtensionEndDate] [date] NULL,
[CpsPreviousEmployerNumber] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceModifiedDate] [date] NULL,
[DwSourceName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DwInsertDate] [datetime] NOT NULL,
[DwInsertUsername] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DwInsertProcessName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DwUpdateDate] [datetime] NOT NULL,
[DwUpdateUsername] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DwUpdateProcessName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
