CREATE TABLE [dbo].[BasIncomingEmployeeDemographic_old]
(
[BasIncomingEmployeeDemographicId] [int] NOT NULL IDENTITY(1, 1),
[EmployerId] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmployeeSsn] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmployeeId] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddingNameOrInitial] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Birthdate] [date] NULL,
[Gender] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address3] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Postal] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[County] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressEffectiveDate] [date] NULL,
[PrimaryPhoneNumber] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WorkPhone] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MobilePhoneNumber] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WorkEmailAddress] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HomeEmailAddress] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginalHireDate] [date] NULL,
[LatestHireDate] [date] NULL,
[EmploymentStatus] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmploymentStatusEffectiveDate] [date] NULL,
[DeathDateAttribute] [date] NULL,
[TerminationDateAttribute] [date] NULL,
[BenefitsEligibilityDate] [date] NULL,
[EmployerDepartmentReporting] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ScheduledHours] [decimal] (7, 2) NULL,
[ScheduledHoursEffectiveDate] [date] NULL,
[BaseAnnualSalaryAcrFactor] [decimal] (30, 2) NULL,
[AnnualCashHousingAllowanceAcrFactor] [decimal] (30, 2) NULL,
[HomeProvidedAmountAcrFactor] [decimal] (30, 2) NULL,
[AnnualCashUtilityAllowanceAcrFactor] [decimal] (30, 2) NULL,
[TotalAcrSumOfThreeAbove] [decimal] (30, 2) NULL,
[AcrEffectiveDate] [date] NULL,
[JobTitleOrClass] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JobTitleOrClassDescription] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SalariedOrHourlyIndicator] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SalariedOrHourlyIndicatorEffectiveDate] [date] NULL,
[RosterNonRosterIndicator] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RosteredOrCommissionedSocialSecurityIndicator] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RosterNonRosterIndicatorEffectiveDate] [date] NULL,
[Salutation] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MaritalStatus] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MaritalStatusEffectiveDate] [date] NULL,
[LawsonEmployeeId] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MissionaryTypeIndicator] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MissionCountryCode] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MissionaryTypeEffectiveDate] [date] NULL,
[BilltoEmployerTaip] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChpCostAndBillingOverride] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CdspCostAndBillingOverride] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VoluntaryBenefitsCostAndBillingOverride] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BillToEmployerExtension] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChpCostAndBillngOverrideEndDate] [date] NULL,
[ChpCostAndBillingOverrideEmployerNumber] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CdspCostAndBillingOverrideEmployerNumber] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VoluntaryBenefitsCostandBillingOverrideEmployerNumber] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VoluntaryBenefitsCostandBillngOverrideEndDate] [date] NULL,
[CrpTraditionalRegularFullBasisIndicator] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CrpTraditionalRegularFullBasisEffectiveDate] [date] NULL,
[Extensiontype] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ExtensionPaidThruDate] [date] NULL,
[ExtensionStartDate] [date] NULL,
[ExtensionEndDate] [date] NULL,
[CpsPreviousEmployerNumber] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceModifiedDate] [date] NULL,
[DwSourceName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DwInsertDate] [datetime] NOT NULL,
[DwInsertUsername] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DwInsertProcessName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DwUpdateDate] [datetime] NOT NULL,
[DwUpdateUsername] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DwUpdateProcessName] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BasIncomingEmployeeDemographic_old] ADD CONSTRAINT [PK__BasIncom__6937FD24544877E0] PRIMARY KEY CLUSTERED ([BasIncomingEmployeeDemographicId]) WITH (FILLFACTOR=90) ON [PRIMARY]
GO
