CREATE TABLE [dbo].[ACQ_HRDEPBEN]
(
[COMPANY] [smallint] NULL,
[EMPLOYEE] [int] NULL,
[DEPENDENT] [smallint] NULL,
[PLAN_TYPE] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PLAN_CODE] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMP_START] [datetime] NULL,
[START_DATE] [datetime] NULL,
[STOP_DATE] [datetime] NULL,
[CREATION_DATE] [datetime] NULL,
[UPD_DATE] [datetime] NULL,
[USER_ID] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TIME_STAMP] [decimal] (6, 0) NULL,
[COVER_TYPE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CREATE_TIME] [decimal] (6, 0) NULL,
[CREATE_USER_ID] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PARTICIPNT] [int] NULL,
[CT_COMPANY] [smallint] NULL,
[CT_EMPLOYEE] [int] NULL,
[CT_DEPENDENT] [smallint] NULL,
[CT_PLAN_TYPE] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CT_PLAN_CODE] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CT_EMP_START] [datetime] NULL,
[CT_START_DATE] [datetime] NULL,
[CHANGE_TYPE] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRIMARYKEY] [char] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwInsertDate] [datetime] NULL,
[DwInsertUsername] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwInsertProcessName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwUpdateDate] [datetime] NULL,
[DwUpdateUsername] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DwUpdateProcessName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
