CREATE TABLE [dbo].[OpenEnrollmentChangeBackup2020Final]
(
[OpenEnrollmentChangeId] [int] NOT NULL IDENTITY(1, 1),
[Employer ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Employee ID] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CPS Member ID] [int] NULL,
[Employee SSN] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First Name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Work Email] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Personal Email] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Current Coverage Effective Date] [date] NULL,
[Current benefit Name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Current Plan Name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Current Tier Option name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Current Elected Amount] [decimal] (11, 2) NULL,
[current pended Amount] [decimal] (11, 2) NULL,
[inforce Benefit Amount] [decimal] (11, 2) NULL,
[Election Cost per Month] [decimal] (11, 2) NULL,
[Employer Cost per month] [decimal] (11, 2) NULL,
[OE Benefit Name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OE Plan Name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OE Tier Option name] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OE Coverage Effective Date] [date] NULL,
[OE Elected Amount] [decimal] (11, 2) NULL,
[OE Amount Pended] [decimal] (11, 2) NULL,
[OE Inforce Initial Benefit Amount] [decimal] (11, 2) NULL,
[OE Election Cost per Month] [decimal] (11, 2) NULL,
[OE Employer Cost per Month] [decimal] (11, 2) NULL,
[Change Type] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceModifiedDate] [date] NULL,
[DwSourceName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DwInsertDate] [datetime] NOT NULL,
[DwInsertUsername] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DwInsertProcessName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DwUpdateDate] [datetime] NOT NULL,
[DwUpdateUsername] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DwUpdateProcessName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
