CREATE TABLE [hub].[ACQ_EmployeeStatementOfBenefits]
(
[EmployeeStatementOfBenefitsId] [int] NULL,
[EmployeeId] [int] NULL,
[MemberName] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AnnualCompensationDate] [datetime] NULL,
[AnnualCompensation] [decimal] (13, 4) NULL,
[ErContributionToChp] [decimal] (13, 4) NULL,
[ErContributionToCdsp] [decimal] (13, 4) NULL,
[ErMatchForCrsp] [int] NULL,
[CrpProjectedAnnualAmount] [int] NULL,
[CrpProjectedAccountBalance] [int] NULL,
[CrpProjectedAnnualDate] [datetime] NULL,
[ChpEnrollmentStatus] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChpOption] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChpParticipation] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CdspEnrollmentStatus] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CdspMonthlyBenefitAmount] [numeric] (16, 6) NULL,
[SbCdspEnrollmentStatus] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SbCdspCurrentParticipation] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SbAipEnrollmentStatus] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SbAipCurrentParticipation] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LsbCdspAmount] [numeric] (32, 0) NULL,
[LsbAipAmount] [decimal] (11, 2) NULL,
[DbCdspEnrolledSpouseAmount] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DbCdspEnrolledDependentAmount] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DbCdspDependentName] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DbAipEnrolledSpouseAmount] [numeric] (13, 3) NULL,
[DbAipCdspEnrolledDependentAmount] [numeric] (13, 3) NULL,
[DbAipCdspDependentName] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CrpEnrollmentStatus] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CrpCurrentParticipation] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CrspEnrollmentStatus] [varchar] (29) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CrspEstimatedDeferralPercent] [int] NULL,
[CrspEstimatedDeferralDate] [datetime] NULL,
[CrspBalanceAmount] [int] NULL,
[CrspBalanceDate] [datetime] NULL,
[EmployeeNumber] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROCESS_LEVEL] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAY_GRADE] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DISPLAY_PLAN_PRECEDENCE] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PLAN_CODE] [char] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccidentEnrollmentStatus] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__ACQ_Emplo__Accid__09746778] DEFAULT (NULL),
[AccidentCurrentCoverage] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__ACQ_Emplo__Accid__0A688BB1] DEFAULT (NULL),
[AccidentCurrentParticipation] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__ACQ_Emplo__Accid__0B5CAFEA] DEFAULT (NULL),
[CritillEmployeeEnrollmentStatus] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__ACQ_Emplo__Criti__0C50D423] DEFAULT (NULL),
[CritillEmployeeCurrentCoverage] [decimal] (19, 4) NULL CONSTRAINT [DF__ACQ_Emplo__Criti__0D44F85C] DEFAULT (NULL),
[CritillSpouseEnrollmentStatus] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__ACQ_Emplo__Criti__0E391C95] DEFAULT (NULL),
[CritillSpouseCurrentCoverage] [decimal] (19, 4) NULL CONSTRAINT [DF__ACQ_Emplo__Criti__0F2D40CE] DEFAULT (NULL),
[CritillChildEnrollmentStatus] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__ACQ_Emplo__Criti__10216507] DEFAULT (NULL),
[CritillChildCurrentCoverage] [decimal] (19, 4) NULL CONSTRAINT [DF__ACQ_Emplo__Criti__11158940] DEFAULT (NULL),
[SupplifeEmployeeEnrollmentStatus] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__ACQ_Emplo__Suppl__1209AD79] DEFAULT (NULL),
[SupplifeEmployeeCurrentCoverage] [decimal] (19, 4) NULL CONSTRAINT [DF__ACQ_Emplo__Suppl__12FDD1B2] DEFAULT (NULL),
[SupplifeSpouseEnrollmentStatus] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__ACQ_Emplo__Suppl__13F1F5EB] DEFAULT (NULL),
[SupplifeSpouseCurrentCoverage] [decimal] (19, 4) NULL CONSTRAINT [DF__ACQ_Emplo__Suppl__14E61A24] DEFAULT (NULL),
[SupplifeChildEnrollmentStatus] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__ACQ_Emplo__Suppl__15DA3E5D] DEFAULT (NULL),
[SupplifeChildCurrentCoverage] [decimal] (19, 4) NULL CONSTRAINT [DF__ACQ_Emplo__Suppl__16CE6296] DEFAULT (NULL)
) ON [PRIMARY]
GO
